spring:
  application:
    name: secmall
  config:
    # 导入外部配置
    import: optional:D:/1A-SOFT/Coding_Project/env/env-dev.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM dual
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 60000