server:
  port: 8010
spring:
  application:
    name: seckill-order
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: localhost:8848
        # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
        service: ${spring.application.name}
        ip: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM dual
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 60000
      idle-timeout: 30000
  redis:
    redisson:
      file: classpath:redisson-cluster.yml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# http://127.0.0.1:8080/actuator/health 各端点地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      # 是否开启。默认为 true 开启。
      enabled: true
      # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
      show-details: always