server:
  port: 8020
spring:
  application:
    name: seckill-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8
    username: user
    password: pass
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM dual
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 60000
      idle-timeout: 30000
  redis:
    redisson:
      file: classpath:redisson-config.yml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl